USER_AGENT = 'MindMimicLabs/1.0'
DOMAIN = 'congress.gov'
ROBOTS = f'https://{DOMAIN}/robots.txt'
URL_VOTE_LIST = f'https://{DOMAIN}/advanced-search/legislation'
URL_VOTE_TEXT = f'https://{DOMAIN}/bill/115th-congress/house-bill/7327/text?format=txt'
